Add a test game
The-Brains/ClickAndPointLib pull request #14
Opened 2017-10-30 00:51 UTC by jacklehamster

2017-10-30 01:29 UTC, Wonay commented
Do you want to make the game into its own repo ? So the library stay light ? You would just have to copy the `demo.html` and `demo.js` and `js/main-demo.js` . If you want to add this game as an extra demo then can you move the file into `game-files-examples` ? And add a html / js to be able to have a URL to hit to test it ?

2017-10-30 01:45 UTC, Wonay commented
I went all the way to the temple after taking the shell and the monkey and the crab, what is happening in the game ?! I want to know the end of the mystery !

2017-10-30 23:31 UTC, leobenkel requested changes
Do you want to make the game into its own repo ? So the library stay light ? You would just have to copy the demo.html and demo.js and js/main-demo.js . If you want to add this game as an extra demo then can you move the file into game-files-examples ? And add a html / js to be able to have a URL to hit to test it ?

2017-10-30 23:31 UTC, leobenkel commented on game/game.json
> +            {
you can more this action inside the global action `takeCrab` so everytime the action of taking the crab is executed , the `hasCrab` variable is set to `true`

2017-11-04 01:53 UTC, jacklehamster commented
How can I import the library to a new repo, can I just lind directly into https://the-brains.github.io/ClickAndPointLib/...?

2017-11-10 23:47 UTC, Wonay commented
yeah, like we did for the other libraries. There is the dist folder you can just import: https://the-brains.github.io/ClickAndPointLib/dist/clickAndPoint.js

2024-07-19 18:16 UTC, jacklehamster commented
Closing. I kinda forgot what this was all about.

2024-07-19 18:16 UTC, closed without merging